### ISSUE TITLE
🟣 Phase 4: CI/CD Integration with GitHub Actions

### ISSUE THREAD

**Issue by MrPeterLee** [inteclab/infrastruture#5]
# 🟣 Phase 4: CI/CD Integration with GitHub Actions

✅ Goals: Leverage existing GitHub self-hosted runners for automated CI/CD.

Fully automate Ansible playbook deployments.

#🚦 CI/CD Setup:

- Configure GitHub Actions workflows (ansible-ci.yml) in infrastructure-ansible.
- Secrets management through GitHub Secrets and Ansible Vault.
- Automated deployment on push to main branch.
- Secure runners with restricted permissions and Ansible roles.

Sample GitHub Actions Workflow:

```yaml
Copy
name: Deploy Ansible Infrastructure

on:
push:
branches: - main

jobs:
ansible-deploy:
runs-on: self-hosted
steps: - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install ansible -y

      - name: Execute Ansible Playbook
        run: |
          echo "${{ secrets.VAULT_PASSWORD }}" > vault_pass.txt
          ansible-playbook -i inventory/production playbooks/bootstrap.yml \
            --vault-password-file vault_pass.txt
```
